### ISSUE TITLE
Adapt mail report template to reference paragraphs from SUISA Tarif S (2020-2023) 

### ISSUE THREAD

**Issue by paraenggu** [radiorabe/suisa_sendemeldung#188]
### Overview

The mail report template shall be adapted to reference certain paragraphs from the SUISA document [Gemeinsamer Tarif S 2020 – 2023](https://www.suisa.ch/dam/jcr:1d82128b-8cc7-4cf0-b0ef-1890ae9d434d/GTS_2020-2023_GER.pdf), as published on the [SUISA Radio and TV](https://www.suisa.ch/en/Kunden/Weitere-Tarife/Radio-und-TV.html) page. It shall be clearly stated, that the report confirms to the terms of the tariff.

### Relevant paragraphs
The following citations are a summary of relevant paragraphs from the [Gemeinsamer Tarif S 2020 – 2023](https://www.suisa.ch/dam/jcr:1d82128b-8cc7-4cf0-b0ef-1890ae9d434d/GTS_2020-2023_GER.pdf) to be referenced within the mail template:

> Gemeinsamer **Tarif S 2020 – 2023**

> **G. Verzeichnisse**
> **31** Die Sender stellen der SUISA die in diesem Abschnitt G aufgeführten Angaben zu. [...]

> **32** Die Sender melden die unter Buchstabe G genannten Programmangaben in elektronischer Form in einem standardisierten importierbaren Format.

> **34** Die Angaben enthalten [...]

> d) Termine
> **45** Alle Angaben sind der SUISA [...] monatlich jeweils bis zum Ende des folgenden Monats zuzustellen. [...]

> **46** Erkennen oder vermuten die SUISA und/oder die SWISSPERFORM Fehler oder Lücken in den Angaben des Senders, beanstanden sie diese innerhalb von drei Monaten gegenüber dem Sender und gewähren diesem eine Nachfrist von 45 Tagen zur Behebung der Mängel.

> **20** Sender, welche ihr System auf die Meldepflichten gemäss Buchstabe G einrichten und korrekt und rechtzeitig nach diesen Meldepflichten melden, erhalten auf der Abrechnung einen Rabatt von 5 %.

#### Proposal from @hairmare 
Hallo SUISA

Im Anhang finden Sie die Sendemeldung von Radio Bern RaBe für den Dezember 2022.

Wir senden ihnen diese Sendemeldung da wir bis Ende 2021 nicht informiert
wurden, dass Radio Bern RaBe im laufenden Jahr von der Meldepflicht befreit ist.

In der Sendungsmeldung enthalten sind die unter Buchstaben G im Tarif
"Gemeinsamer Tarif S 2020 - 2023" genannten Programmangaben in elektronischer
Form. Es handelt sich bei der Datei um eine Comma-Separated Values (CSV)
Datei welche dem RFC 4180 Standard folgt.

Diese Sendemeldung enthält unter anderem folgende Angaben:

- Titel des Musikwerks
- Name des Komponisten
- Name des bzw. der Hauptinterpreten
- Label
- ISRC
- vom Sender der Aufnahme selbst zugewiesene Identifikationsnummer
- Sendezeit
- Sendedauer

Die Datei folgt nach bestem Wissen und Gewissen und wo dies technisch möglich
ist der Vorlage in "Gemeinsamer Tarif S 2020 - 2023" S. 15 ff.

Das Feld ISRC ist dabei mindestens in Fällen wo der ISRC zusammen mit der Aufnahme
vom Lieferanten der Aufnahme in irgendeiner Form mitgeteilt bzw. mitgeliefert
wurde angegeben. Wir ergänzen diese Angaben wo möglich aus unseren eigenen
Datenbeständen und arbeiten zu diesem Zweck auch mit externen Partnern zusammen.
Nachmeldungen und Korrekturen von ISRC werden wir selbstverständlich sofort
verarbeiten und ihnen mitteilen.

Wir bitten sie höflich uns den Erhalt wie auch die erfolgreiche, automatisierte
Verarbeitung dieser Sendemeldung zu bestätigen. Bitte kontaktieren sie uns
dringlich und unverzüglich falls diese Sendemeldung Mängel wie Inkorrektheit
oder andere Missstände wie Fehler oder Lücken aufweist. Beanstandungen zu dieser
Sendemeldung lassen sie uns bitte in den nächsten drei Monaten vor dem 31. März 2023
zukommen. Im Falle einer Beanstandung streben wir an etwaige Mängel raschmöglichst
innerhalb der Nachfrist von 45 Tagen zu beheben.

Diese Email wurde automatisch generiert. Bei vertraglichen Fragen erreichen
sie uns an besten zu Bürozeiten unter 012 345 67 89. Technische Anliegen
im Zusammenhang mit der Sendemeldung melden sie bitte ebenda oder bevorzugt
direkt per Email an test@example.org.

Freundliche Grüsse,
Radio Bern RaBe

**Comment by hairmare** [comment]
ooo, i missed '''46''', i think i have the others covered in my draft #189

**Comment by hairmare** [comment]
updated my draft and also copied it's result into the proposal section above

this i don't explicitly mention is the rebate explicitly ala "we looking foward to receiving 5%", i'm also not namedropping SWISSPERFORM

for "standardisierten importierbaren Format." i also start adhering to RFC 4180 for #187.

we could add a something alluding to the fact that we'd happily use a more modern format than csv over smtp. heck, i'd even implement a soap client if they consider that modern and anything XML/JSON style would be more than easy for us.

**Comment by paraenggu** [comment]
Slightly modified proposal based on the original one from @hairmare 

> Hallo SUISA
> 
> Im Anhang finden Sie die Sendemeldung von $station_name für den $month $year. 
> 
> Die Sendmeldung erfüllt die Bestimmungen und Pflichten gemäss dem Dokument "Gemeinsamer Tarif S 2020 - 2024" [1]. 
> 
> Die Einreichfrist für den Montat $month würde gemäss Ziffer 45 eingehalten.
> 
> In der Sendungsmeldung enthalten sind die unter Buchstaben G (Verzeichnisse) des Tarifs genannten Programmangaben, in elektronischer Form. Die Angaben richten sich nach dem standardisierten Format gemäss der "Vorlage für Sendemeldungen: Gemeinsamer Tarif S" [2] sowie den Abstimmung zwischen SUSIA und $station_name.
> 
> 
> Diese Sendemeldung enthält unter anderem die unter Ziffer 34 geforderten Angaben:
> 
> - Titel des Musikwerks
> - Name des Komponisten
> - Name des bzw. der Hauptinterpreten
> - Label
> - ISRC der benützten Aufnahme 
> - vom Sender der Aufnahme selbst zugewiesene Identifikationsnummer
> - Sendezeit
> - Sendedauer
> 
> 
> Allfällige Beanstandungen oder technische Rückfragen zu dieser Sendemeldung müssen in schriftlicher, elektronischer Form an suisa@example.org gerichtet werden. 
> 
> Beanstandungen müssen, gemäss Ziffer 46, bis spätestens in drei Monaten vor dem YYYY-MM-DD erfolgen. Anschliessend gilt die Sendemeldung für $month als akzeptiert.
> 
> Korrekt und termingerecht gemeldete Beanstandungen werden unter Berücksichtigung der Nachfrist von 45 Tagen, gemäss Ziffer 46, bearbeitet.
> 
> 
> Diese Email und Sendmeldung wurde automatisch generiert.
> 
> 
> Freundliche Grüsse,
> $station_name
> 
> 
> FOOTER MIT ADDRESSE UND TELEFON
> 
> 
> [1] https://www.suisa.ch/dam/jcr:1d82128b-8cc7-4cf0-b0ef-1890ae9d434d/GTS_2020-2024_GER.pdf
> [2] https://www.suisa.ch/dam/jcr:6934be98-4319-4565-8936-05007d83fd35/Vorlage_fuer_Sendemeldungen__GTS__2020-2022.xlsx

**Comment by hairmare** [comment]
I'll create a PR that also contains +/- the following addendum to @paraenggu's proposal and then we can edit from there

```diff
--- pareaanggu	2023-02-17 15:07:44.286695096 +0100
+++ hairmare	2023-02-17 15:10:22.009019050 +0100
@@ -2,8 +2,8 @@
 
 Im Anhang finden Sie die Sendemeldung von $station_name für den $month $year. 
 
-Die Sendemeldung erfolgt gemäss den Bestimmungen "Gemeinsamer Tarif S 2020 - 2024" [1] unter 
-Einhaltung der Einreichfirst für den Montat $month gemäss Ziffer 45 des Tarifs. 
+Diese Sendemeldung erfolgt gemäss den Bestimmungen "Gemeinsamer Tarif S 2020 - 2024" [1] unter 
+Einhaltung der Einreichefrist für den Monat $month gemäss Ziffer 45 des Tarifs. 
 
 In der Sendungsmeldung enthalten sind die unter Buchstaben G (Verzeichnisse) des Tarifs genannten Programmangaben, in elektronischer Form. Die Angaben richten sich nach dem standardisierten Format gemäss der "Vorlage für Sendemeldungen: Gemeinsamer Tarif S" [2] sowie den Abstimmung zwischen SUSIA und $station_name.
 
@@ -20,9 +20,9 @@
 - Sendedauer
 
 
-Allfällige Beanstandungen oder technische Rückfragen zu dieser Sendemeldung müssen in schriftlicher, elektronischer Form an suisa@example.org gerichtet werden. 
+Allfällige Beanstandungen oder technische Rückfragen zu dieser Sendemeldung müssen in schriftlicher, elektronischer Form an $responsible_mail gerichtet werden. 
 
-Beanstandungen müssen, gemäss Ziffer 46, bis spätestens in drei Monaten vor YYYY-MM-DD erfolgen. Anschliessend gilt die Sendemeldung für $month als akzeptiert und die Tarifbestimmungen als eingehalten.
+Beanstandungen müssen, gemäss Ziffer 46, bis spätestens in drei Monaten vor dem $in_three_months erfolgen. Anschliessend gilt die Sendemeldung für $month als akzeptiert und die Tarifbestimmungen als eingehalten.
 
 Korrekt und termingerecht gemeldete Beanstandungen werden unter Berücksichtigung der Nachfrist von 45 Tagen, gemäss Ziffer 46, bearbeitet.
 
@@ -33,9 +33,9 @@
 Freundliche Grüsse,
 $station_name
 
+-- 
+$mail_footer
 
-FOOTER MIT ADRESSE
 
-
-[1] https://www.suisa.ch/dam/jcr:1d82128b-8cc7-4cf0-b0ef-1890ae9d434d/GTS_2020-2024_GER.pdf
-[2] https://www.suisa.ch/dam/jcr:6934be98-4319-4565-8936-05007d83fd35/Vorlage_fuer_Sendemeldungen__GTS__2020-2022.xlsx
+[1] <https://www.suisa.ch/dam/jcr:1d82128b-8cc7-4cf0-b0ef-1890ae9d434d/GTS_2020-2024_GER.pdf>
+[2] <https://www.suisa.ch/dam/jcr:6934be98-4319-4565-8936-05007d83fd35/Vorlage_fuer_Sendemeldungen__GTS__2020-2022.xlsx>

```
