### ISSUE TITLE
Support custom files

### ISSUE THREAD

**Issue by spameier** [radiorabe/suisa_sendemeldung#200]
Some of our files are not in the database and require a manual upload to ACRCloud. The recorded metadata are then returned in an array `custom_files`:

```json
    {
        "status": {
            "msg": "Success",
            "code": 0,
            "version": "1.0"
        },
        "result_type": 0,
        "metadata": {
            "timestamp_utc": "2023-01-31 14:44:51",
            "played_duration": 507,
            "type": "delay",
            "custom_files": [
                {
                    "album": "",
                    "play_offset_ms": 17320,
                    "sample_begin_time_offset_ms": 1140,
                    "score": 89,
                    "title": "Future Shock (Club Mix)",
                    "release_date": "",
                    "Artist": "STARTER",
                    "sample_end_time_offset_ms": 9740,
                    "count": 49,
                    "label": "",
                    "db_end_time_offset_ms": 17320,
                    "bucket_id": "16272",
                    "db_begin_time_offset_ms": 8720,
                    "artists": "STARTER",
                    "duration_ms": 524817,
                    "isrc": "CHAAA2116394",
                    "acrid": "22f5455cd10e288a30a1aabf3144938a"
                }
            ],
            "timestamp_local": "2023-01-31 14:44:51"
        }
    },
```

These additional metadata should also be recorded by the script.

**Comment by spameier** [comment]
Already implemented https://github.com/radiorabe/suisa_sendemeldung/blob/8d646d0358e5794668a2054d3de402b9f2de0f3c/suisa_sendemeldung/suisa_sendemeldung.py#L294-L298

**Comment by hairmare** [comment]
The implementation is a bit rough around the edges since the custom_file and music entries don't follow the same schema.

I've been focussing on getting this month report done but have a version of acrclient locally  that typifiys the response into a bunch of python classes that i plan on pushing soon. I think it'll help us understand the structures form ACRCloud much better.
